# Generated by Django 5.1.1 on 2024-10-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_quantity_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='absolute_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
